title: "Wookyung Chung's Website"
email: ujon@kanto-gakuen.ac.jp
description: >-
  Wookyung Chung (鄭宇景 in Kanji) Associate Professor, Department of Economics, Kanto Gakuen University.
baseurl: ""
url: "https://www.wkchung.com"

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter
