title: "Wookyung Chung's Website"
email: ujon@kanto-gakuen.ac.jp
description: >-
  Wookyung Chung (鄭宇景 in Kanji) Associate Professor, Department of Economics, Kanto Gakuen University.
baseurl: ""
url: "https://chungwookyung.github.io"

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter

# GitHub Pages settings
repository: ChungWookyung/wkchungWEBSITE
